// SPDX-FileCopyrightText: Loren Burkholder
//
// SPDX-License-Identifier: GPL-3.0

#include "DGen.h"

#include <iostream>

#include "CppBindingGenerator.h"
#include "Utils.h"

std::string DGen::getDFileHeader(const std::string &moduleName)
{
    if (moduleName.size() <= 0)
        throw std::runtime_error("Null module name was passed");

    auto t = std::time(nullptr);
    std::string timeStr = std::asctime(std::localtime(&t));
    return std::format(
        R"(// *** WARNING: autogenerated file, do not modify. Changes will be overwritten. ***
// Generated by Polyglot version {} at {}.
// This file contains symbols that have been exported from other languages into D.

module {};

@nogc:)",
        POLYGLOT_VERSION,
        timeStr.substr(0, timeStr.size() - 1), // remove the '\n'
        moduleName);
}

std::string DGen::getDFileFooter()
{
    return {};
}

std::string DGen::getDTypeString(const clang::QualType &type, const clang::Decl *decl)
{
    std::string typeString;
    if (type.isConstQualified())
        typeString += "const ";

    if (type->isVoidType() || type->isVoidPointerType())
        typeString += "void";
    if (type->isBooleanType())
        typeString += "bool";
    else if (type->isCharType())
        typeString += "char";
    else if (type->isChar16Type() || type->isWideCharType())
        typeString += "wchar";
    else if (type->isChar32Type())
        typeString += "dchar";
    else if (type->isIntegerType())
    {
        if (!Utils::isFixedWidthIntegerType(type))
        {
            auto &diagnostics = decl->getASTContext().getDiagnostics();
            auto id = diagnostics.getDiagnosticIDs()->getCustomDiagID(clang::DiagnosticIDs::Warning,
                                                                      std::format("Use fixed-width integer types for "
                                                                                  "portablility"));
            diagnostics.Report(decl->getBeginLoc(), id);
        }

        if (type->isUnsignedIntegerType())
            typeString += 'u';

        auto size = decl->getASTContext().getTypeSize(type);
        switch (size)
        {
        case 8:
            typeString += "byte";
            break;
        case 16:
            typeString += "short";
            break;
        case 32:
            typeString += "int";
            break;
        case 64:
            typeString += "long";
            break;
        case 128:
            typeString += "cent";
            break;
        default:
            throw std::runtime_error(std::string("Unrecognized integer size: ") + std::to_string(size));
        }
    }
    else if (type->isFloatingType())
    {
        auto size = decl->getASTContext().getTypeSize(type);
        switch (size)
        {
        case 32:
            typeString += "float";
            break;
        case 64:
            typeString += "double";
            break;
        case 128:
            typeString += "real";
            break;
        default:
            throw std::runtime_error(std::string("Unrecognized floating-point size: ") + std::to_string(size));
        }
    }
    else if (auto enumType = type->getAs<clang::EnumType>(); enumType)
        typeString += enumType->getDecl()->getNameAsString();
    else if (Utils::isStdString(type))
        typeString += "basic_string";

    typeString += ' ';
    if (type->isPointerType())
        typeString += '*';

    return typeString;
}

std::string DGen::getDExprValueString(const clang::Expr *defaultValue, const clang::ASTContext &context)
{
    clang::Expr::EvalResult result;
    if (!defaultValue->EvaluateAsConstantExpr(result, context))
        throw std::runtime_error("Failed to evaluate expression");

    //    if (result.Val.isNullPointer())
    //        return "null";

    std::string retval;
    llvm::raw_string_ostream stream(retval);
    defaultValue->printPretty(stream, nullptr, clang::PrintingPolicy(context.getLangOpts()));
    return retval;
}
